### ISSUE TITLE
Error: Failed to get GPU adapter

### ISSUE THREAD

**Issue by omeiirr** [dmtrKovalenko/subtitler#12]
I tried running this in Chrome, Edge, and Brave after enabling the --enable-unsafe-webgpu flag, but I'm still getting this error. 

```
Transcription failed
no available backend found. ERR: [webgpu] Error: Failed to get GPU adapter. You may need to enable flag "--enable-unsafe-webgpu" if you are using Chrome.
Error: no available backend found. ERR: [webgpu] Error: Failed to get GPU adapter. You may need to enable flag "--enable-unsafe-webgpu" if you are using Chrome.
    at Ts (https://subtitles.fframes.studio/assets/whisper-worker-0j9JtY_t.js:5:1599)
    at async W0.create (https://subtitles.fframes.studio/assets/whisper-worker-0j9JtY_t.js:5:17973)
```

I'm using Arch Linux with an NVIDIA card.

```
❯ neofetch
                     ./o.                  omeir@omeir-eos 
                   ./sssso-                --------------- 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: HP Pavilion Notebook 
             `-/ossssssssssssso/.          Kernel: 6.9.7-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 14 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1159 (pacman), 26 (flatpak) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.2.26 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080 
    .:///ossssssssssssssssssssssssso++:    Terminal: /dev/pts/0 
  `:////ssssssssssssssssssssssssssso+++.   CPU: Intel i5-8300H (8) @ 4.000GHz 
`-////+ssssssssssssssssssssssssssso++++-   GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
 `..-+oosssssssssssssssssssssssso+++++/`   GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
   ./++++++++++++++++++++++++++++++/:.     Memory: 1615MiB / 7750MiB 
  `:::::::::::::::::::::::::------``       GPU Driver: Hewlett-Packard Company Device [103c:84f8] 
                                           CPU Usage: 21% 
                                           Disk (/): 47G / 58G (85%) 
                                           Battery0: 100% [Full] 

```

I also checked that the Nvidia GPU is active.
```
❯ nvidia-smi
Thu Oct 24 20:45:54 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58                 Driver Version: 555.58         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     On  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8             N/A / ERR!  |     144MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1516      G   /usr/lib/Xorg                                  83MiB |
|    0   N/A  N/A      1600      G   /usr/bin/gnome-shell                           34MiB |
|    0   N/A  N/A      2144      G   /usr/lib/xdg-desktop-portal-gnome              10MiB |
|    0   N/A  N/A     15525      G   /usr/bin/kgx                                    9MiB |
+-----------------------------------------------------------------------------------------+


❯ envycontrol -q
nvidia

```

Any idea what could be going wrong?

**Comment by dmtrKovalenko** [comment]
have you tried any other webgpu demos/examples like this for example https://webgpu.github.io/webgpu-samples/

**Comment by dmtrKovalenko** [comment]
and by the way it is weird it is failling if the adapter is not found, it should fallback to the CPU wasm mode

**Comment by omeiirr** [comment]
Ooh I didn't know about the WebGPU demo.

I running the unstable build of Chrome using this command `google-chrome-unstable --enable-unsafe-webgpu --enable-features=Vulkan`.

The demo site is working now, but your website has a new error:

```
Transcription failed
no available backend found. ERR: [webgpu] TypeError: e.requestAdapterInfo is not a function
Error: no available backend found. ERR: [webgpu] TypeError: e.requestAdapterInfo is not a function
    at Ts (https://subtitles.fframes.studio/assets/whisper-worker-0j9JtY_t.js:5:1599)
    at async W0.create (https://subtitles.fframes.studio/assets/whisper-worker-0j9JtY_t.js:5:17973)
```

**Comment by dmtrKovalenko** [comment]
I'll check it out
